### ISSUE TITLE
Fails to compile with Go 1.19~rc2

### ISSUE THREAD

**Issue by subpop** [peterbourgon/ff#96]
Fedora 37 (due to be released in the fall of 2022) updated to Go 1.19~rc2. The ff package started failing to compile; it looks like there's a breaking API change in the errors package:

```
./command_test.go:391:55: second argument to errors.As should not be *error
./command_test.go:409:51: second argument to errors.As should not be *error
```

You can see the full build log [here](https://bugzilla-attachments.redhat.com/attachment.cgi?id=1901466) and the automatically reported FTBFS bug [here](https://bugzilla.redhat.com/show_bug.cgi?id=2113344).

**Comment by jolheiser** [comment]
This can be "solved" by changing `error` to `any` (or `interface{}` in order to avoid changing `go.mod`) for the `-As` fields here
https://github.com/peterbourgon/ff/blob/ec0e9e83d7894c370f9f377bf634527eaf182ad0/ffcli/command_test.go#L328-L334

I don't particularly like using `any`, which is less clear than `error`, but this is the sacrifice the `go vet` gods have demanded.

Let me know if you'd like a PR with these changes, but it may be worth a different refactor. Using `any` just seems like a code smell workaround.

**Comment by peterbourgon** [comment]
Wow, frustrating!

**Comment by peterbourgon** [comment]
https://github.com/peterbourgon/ff/releases/tag/v3.3.0
